spring:
#  security:
#    enable-csrf: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true         #是否开启注册中心路由功能
          lower-case-service-id: true
      routes:
        - id: authority #路由ID，唯一即可
          uri: lb://wifi-upgrade-authority   #要转到的地址（静态路由：ip地址http://localhost:8086  动态路由：注册后的服务名称）
          predicates:
            - Path=/theAuthority/permission/**
          filters:
            - StripPrefix=1
#
#        - id: device
#          uri: lb://device
#          predicates:
#            - Path=/front-device/**
#          filters:
#            - StripPrefix=1

#nacos配置中心test
test-nacos:
  test: 1234