spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true         #是否开启注册中心路由功能
#          lower-case-service-id: true
      routes:
        - id: authority-HHH #路由ID，唯一即可
          uri: http://localhost:8086 #要转到的地址（静态路由：ip地址  动态路由：注册后的服务名称）
          predicates:
            - Path=/permission/permissions/listAll  #断言，路径相匹配的进行路由