spring:
  #  security:
  #    enable-csrf: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true         #是否开启注册中心路由功能
          lower-case-service-id: true
      routes:
        - id: authority #路由ID，唯一即可
          uri: lb://wifi-upgrade-authority   #要转到的地址（静态路由：ip地址http://localhost:8086  动态路由：注册后的服务名称）
          predicates:
            - Path=/theAuthority/permission/**
          filters:
            - StripPrefix=1
#
#        - id: device
#          uri: lb://device
#          predicates:
#            - Path=/front-device/**
#          filters:
#            - StripPrefix=1

#nacos配置中心test
test-nacos:
  test: 1234


secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/mall-auth/oauth/token"
      - "/mall-auth/rsa/publicKey"
      - "/mall-search/**"
      - "/mall-portal/sso/login"
      - "/mall-portal/sso/register"
      - "/mall-portal/sso/getAuthCode"
      - "/mall-portal/home/**"
      - "/mall-portal/product/**"
      - "/mall-portal/brand/**"
      - "/mall-admin/admin/login"
      - "/mall-admin/admin/register"
      - "/mall-admin/minio/upload"