spring:
  #  security:
  #    enable-csrf: false
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true         #是否开启注册中心路由功能
          lower-case-service-id: true
      routes:
        - id: authority #路由ID，唯一即可
          uri: lb://${auth-server.name}   #要转到的地址（静态路由：ip地址http://localhost:8086  动态路由：注册后的服务名称）
          predicates:
            - Path=/system/**,/auth/**
#          filters:
#            - StripPrefix=1

        - id: device
          uri: lb://device
          predicates:
            - Path=/device/**



#nacos配置中心test
test-nacos:
  test: 1234


secure:
  ignore:
    urls: #配置白名单路径
      - /system/users/register
      - /system/users/login
      - /system/users/logout
      - /auth/test/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - "/doc.html"


auth-server:
  name: wifi-upgrade-authority  #注册中心注册的auth模块名字

logging:
  level:
    com.alibaba.nacos.client.*: WARN