server:
  port: 9001

spring:
  application:
    name: wifi-upgrade-gateway
  profiles:
    active: dev
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: wifi-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'theTest '  #JWT负载中拿到开头，token前缀
  userInfoHead: userInfo #用户信息请求头

redis:
  key:
    allPermission: 'auth:AllPermission'
    userPermissionRelation: 'auth:UserPermissionRelation'