server:
  port: 8086

spring:
  application:
    name: authority
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: authority-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'theTest '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /permission/users/register
      - /permission/users/login
      - /permission/users/logout
      - /user/info
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**

# 禁止Actuator监控Redis连接
management:
  health:
    redis:
      enabled: false

#账户锁定配置信息 (eg:30min内5次失败，锁定60min)
login-lock-info:
  range-time: 2          #允许最多失败次数的时间范围，min
  max-fail-count: 5       #允许的最多失败次数
  maintain-lock-time: 3    #锁定维持的时间，min